spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

jwt:
  secret: ${SECRET-KEY}
  expiration: 86400000

logging:
  level:
    root: INFO
