spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080

jwt:
  secret: ${SECRET-KEY}
  expiration: 86400000

logging:
  level:
    root: INFO
